# Generated by Django 5.2.11 on 2026-02-18 07:33

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Максимальный размер: 5МВ', null=True, upload_to='categories/', validators=[backend.validators.validate_image_size], verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Максимальный размер: 5МВ', null=True, upload_to='products/', validators=[backend.validators.validate_image_size], verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Максимальный размер: 5МВ', null=True, upload_to='subcategories/', validators=[backend.validators.validate_image_size], verbose_name='Изображение'),
        ),
    ]
